name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - .github/**
  pull_request:
    branches:
      - master
    paths-ignore:
      - .github/**
  schedule:
    - cron: '0 2 12,26 * *'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: "Python tests"
        run: |
          pytest tests
      - name: "Python PEP8"
        run: |
          pycodestyle --ignore=E501 .
