name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - .github/**
  pull_request:
    branches:
      - master
    paths-ignore:
      - .github/**
  schedule:
    - cron: '0 2 12,26 * *'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: "Python tests"
        run: |
          pytest tests
          echo "PYTEST_RC=$?" >> $GITHUB_ENV
      - name: "Python PEP8"
        if: always()
        run: |
          pycodestyle --ignore=E501 .
      - name: "RocketChat notification"
        run: |
          PYTEST_RC=${{ env.PYTEST_RC }}
          if [ $PYTEST_RC -eq 0 ]; then
            MSG=":money_with_wings: *VAT* library tests completed successfully :white_check_mark:"
          else
            MSG=":warning: :money_with_wings: *VAT* library tests failed :x:"
          fi
          curl -X POST -H 'Content-Type: application/json' \
            -d '{"text": "'"$MSG"'", "username": "GHA", "channel": "#mergado_cicd", "icon_emoji": ":mergadodevsbot:"}' \
            ${{ secrets.ROCKETCHAT_WEBHOOK }}
